### ISSUE TITLE
unable to use it

### ISSUE THREAD

**Issue by lorvent** [pehaa/gridsome-starter-wordpress-bootstrap#1]
Hello,
very excited to try it...but when i try, i get following error

```
Gridsome v0.6.7

Initializing plugins...
Initialize - 1.66s
Loading data from http://original-domain.com
TypeError: Cannot destructure property `status` of 'undefined' or 'null'.
    at WordPressSource.fetch (C:\laragon\www\my-gridsome-wp-site\src\plugins\wp-source\index.js:199:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by pehaa** [comment]
Hi, it seems to be a problem related to your original site. What is the response from http://original-domain.com/wp-json/wp/v2/types/ ?

**Comment by lorvent** [comment]
Hello,

this is the output

```
{
"post": {
"description": "",
"hierarchical": false,
"name": "Posts",
"slug": "post",
"taxonomies": [
"category",
"post_tag",
"series"
],
"rest_base": "posts",
"_links": {
"collection": [
{
"href": "http://original-domain.com/wp-json/wp/v2/types"
}
],
"wp:items": [
{
"href": "http://original-domain.com/wp-json/wp/v2/posts"
}
],
"curies": [
{
"name": "wp",
"href": "https://api.w.org/{rel}",
"templated": true
}
]
}
},
"page": {
"description": "",
"hierarchical": true,
"name": "Pages",
"slug": "page",
"taxonomies": [],
"rest_base": "pages",
"_links": {
"collection": [
{
"href": "http://original-domain.com/wp-json/wp/v2/types"
}
],
"wp:items": [
{
"href": "http://original-domain.com/wp-json/wp/v2/pages"
}
],
"curies": [
{
"name": "wp",
"href": "https://api.w.org/{rel}",
"templated": true
}
]
}
},
"attachment": {
"description": "",
"hierarchical": false,
"name": "Media",
"slug": "attachment",
"taxonomies": [],
"rest_base": "media",
"_links": {
"collection": [
{
"href": "http://original-domain.com/wp-json/wp/v2/types"
}
],
"wp:items": [
{
"href": "http://original-domain.com/wp-json/wp/v2/media"
}
],
"curies": [
{
"name": "wp",
"href": "https://api.w.org/{rel}",
"templated": true
}
]
}
},
"wp_block": {
"description": "",
"hierarchical": false,
"name": "Blocks",
"slug": "wp_block",
"taxonomies": [],
"rest_base": "blocks",
"_links": {
"collection": [
{
"href": "http://original-domain.com/wp-json/wp/v2/types"
}
],
"wp:items": [
{
"href": "http://original-domain.com/wp-json/wp/v2/blocks"
}
],
"curies": [
{
"name": "wp",
"href": "https://api.w.org/{rel}",
"templated": true
}
]
}
},
"feedback": {
"description": "",
"hierarchical": false,
"name": "Feedback",
"slug": "feedback",
"taxonomies": [],
"rest_base": "feedback",
"_links": {
"collection": [
{
"href": "http://original-domain.com/wp-json/wp/v2/types"
}
],
"wp:items": [
{
"href": "http://original-domain.com/wp-json/wp/v2/feedback"
}
],
"curies": [
{
"name": "wp",
"href": "https://api.w.org/{rel}",
"templated": true
}
]
}
},
"jp_pay_order": {
"description": "Simple Payments orders",
"hierarchical": false,
"name": "Order",
"slug": "jp_pay_order",
"taxonomies": [],
"rest_base": "jp_pay_order",
"_links": {
"collection": [
{
"href": "http://original-domain.com/wp-json/wp/v2/types"
}
],
"wp:items": [
{
"href": "http://original-domain.com/wp-json/wp/v2/jp_pay_order"
}
],
"curies": [
{
"name": "wp",
"href": "https://api.w.org/{rel}",
"templated": true
}
]
}
},
"jp_pay_product": {
"description": "Simple Payments products",
"hierarchical": false,
"name": "Product",
"slug": "jp_pay_product",
"taxonomies": [],
"rest_base": "jp_pay_product",
"_links": {
"collection": [
{
"href": "http://original-domain.com/wp-json/wp/v2/types"
}
],
"wp:items": [
{
"href": "http://original-domain.com/wp-json/wp/v2/jp_pay_product"
}
],
"curies": [
{
"name": "wp",
"href": "https://api.w.org/{rel}",
"templated": true
}
]
}
}
}
```

**Comment by lorvent** [comment]
Hello another update,
this time i changed wordpress site url (different website)
and locally when i tried `gridsome develop` it worked fine and i can preview website

but when i try same in netlify, i get following error

```
12:53:52 AM: Error: ECONNREFUSED - /wp-json/wp/v2/types
12:53:52 AM:     at WordPressSource.fetch (/opt/build/repo/src/plugins/wp-source/index.js:195:15)
12:53:52 AM:     at process._tickCallback (internal/process/next_tick.js:68:7)
12:53:52 AM: Skipping functions preparation step: no functions directory set
```

any idea why it works locally but not on netlify?

thanks

**Comment by Triloworld** [comment]
Check if Netlify is block from access "/wp-json/wp/v2/types" on your wordpress instalation.

Your JSON don't inlcude "status" field as is normally available - my have it:
> "status": "publish",
